### ISSUE TITLE
Tool does not respect relative path if called from different folder

### ISSUE THREAD

**Issue by serjek** [lix-pm/haxeshim#31]
1. Have a `build.hxml` and `build_base.hxml` on root of your project
2. Add line `build_base.hxml` to `build.hxml` to include it to build
3. `haxe build.hxml` works fine while `haxe ../build.hxml` called from 1 level deep directory results in error `no such file: /path/to/deep/directory/build_base.hxml`. Current workaround is `cd .. && haxe build.hxml && cd deepdirectory`

**Comment by back2dos** [comment]
Well, that is the normal behavior of how haxe resolves paths ... but I'll think of something to explicitly reference other hxmls by paths relative to the current hxml, because I can definitely see how that would be useful. That said, this opens another host of questions like: relative to what should the relative paths in the included hxmls be used?

Simplest solution would be to have a pseudo environment variable that you can use in all paths (class paths, output paths, hxml include paths), e.g. `${__dirname}/build_base.hxml`.

**Comment by back2dos** [comment]
You can use `${__dirname}` in hxmls for building paths relative to the hxml.
